### ISSUE TITLE
执行代码分析的时候报错

### ISSUE THREAD

**Issue by hgq520** [nicejade/vue-boilerplate-template#12]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\nodeJs\\node.exe',
1 verbose cli   'D:\\nodeJs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'analyz' ]
2 info using npm@4.1.2
3 info using node@v7.6.0
4 verbose run-script [ 'preanalyz', 'analyz', 'postanalyz' ]
5 info lifecycle vue-boilerplate-template@3.1.0~preanalyz: vue-boilerplate-template@3.1.0
6 silly lifecycle vue-boilerplate-template@3.1.0~preanalyz: no script for preanalyz, continuing
7 info lifecycle vue-boilerplate-template@3.1.0~analyz: vue-boilerplate-template@3.1.0
8 verbose lifecycle vue-boilerplate-template@3.1.0~analyz: unsafe-perm in lifecycle true
9 verbose lifecycle vue-boilerplate-template@3.1.0~analyz: PATH: D:\nvm\v7.6.0\node_modules\npm\bin\node-gyp-bin;E:\00LEarnTest\vue-boilerplate-template-master\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;D:\eclipse\JDK1.6\bin;D:\eclipse\JDK1.6\jre\bin;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;D:\nvm;D:\nodeJs;C:\Users\haoguoqi\AppData\Roaming\npm;D:\nodeJs;D:\Microsoft VS Code\bin;C:\Users\haoguoqi\AppData\Local\Programs\Fiddler;C:\Users\haoguoqi\AppData\Local\GitHubDesktop\bin;D:\nvm;D:\nodeJs
10 verbose lifecycle vue-boilerplate-template@3.1.0~analyz: CWD: E:\00LEarnTest\vue-boilerplate-template-master
11 silly lifecycle vue-boilerplate-template@3.1.0~analyz: Args: [ '/d /s /c',
11 silly lifecycle   'NODE_ENV=production npm_config_report=true npm run build' ]
12 silly lifecycle vue-boilerplate-template@3.1.0~analyz: Returned: code: 1  signal: null
13 info lifecycle vue-boilerplate-template@3.1.0~analyz: Failed to exec analyz script
14 verbose stack Error: vue-boilerplate-template@3.1.0 analyz: `NODE_ENV=production npm_config_report=true npm run build`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\nvm\v7.6.0\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:192:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\nvm\v7.6.0\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:192:7)
14 verbose stack     at maybeClose (internal/child_process.js:890:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vue-boilerplate-template@3.1.0
16 verbose cwd E:\00LEarnTest\vue-boilerplate-template-master
17 error Windows_NT 6.1.7601
18 error argv "D:\\nodeJs\\node.exe" "D:\\nodeJs\\node_modules\\npm\\bin\\npm-cli.js" "run" "analyz"
19 error node v7.6.0
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error vue-boilerplate-template@3.1.0 analyz: `NODE_ENV=production npm_config_report=true npm run build`
22 error Exit status 1
23 error Failed at the vue-boilerplate-template@3.1.0 analyz script 'NODE_ENV=production npm_config_report=true npm run build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue-boilerplate-template package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     NODE_ENV=production npm_config_report=true npm run build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue-boilerplate-template
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue-boilerplate-template
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by nicejade** [comment]
这是一个令人不解的问题，我在 `OS X` 系统，分别用 `NodeJs` 的 _6.3.1_  _7.6.0_  以及 _10.0.0_ 尝试运行了 `yarn run analyz` 命令，都得到了期望的结果；从您给出的错误消息，可以看出您使用的 `Windows` 系统，暂时我无法使用此类型机器进行尝试；我在 [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer/) 寻求答案，暂时却未得到有价值信息。不知您可以否升级 `Node` 至 `v8.*`   进行下尝试呢？希望可以听到您成功运行的反馈。
