### ISSUE TITLE
Change index.ejs to index.html

### ISSUE THREAD

**Issue by everlose** [nicejade/vue-boilerplate-template#2]
I just find a plugin for index.html to add dynamic path 'vender.dll.js', comes across this issue: https://github.com/SimenB/add-files-html-webpack-plugin    ,no more need ejs at all。

**Comment by nicejade** [comment]
@everlose Sorry, the reply is late. Is really a great idea to use the plugins you recommend . However, according to my observation it also has some limitations；For example, it seems powerless when I want to inject pwa related functionality. Like this:

```
<% for (var chunk of webpack.chunks) {
  for (var file of chunk.files) {
    if (file.match(/\.(js|css)$/)) { %>
<link rel="<%= chunk.initial ? 'preload' : 'prefetch' %>" href="<%= htmlWebpackPlugin.files.publicPath + file %>" as="<%= file.match(/\.css$/)?'style':'script' %>">
<% }}} %>
```
Or can also found here：https://github.com/nicejade/vue-boilerplate-template/blob/master/index.ejs#L20-L29, Look forward to more of your views .
