### ISSUE TITLE
babel-polyfill

### ISSUE THREAD

**Issue by jessjava** [nicejade/vue-boilerplate-template#26]
入口的src/main.js中为什么要引入 ‘babel-polyfill’呢，是不是多余了。因为babelrc里面已经存在‘transform-runtime’插件了。

**Comment by nicejade** [comment]
的确，全量引入 `babel-polyfill`，确实不是一个好的选择，因此自从 `Babel 7.4.0`，[babel-polyfill](https://babeljs.io/docs/en/babel-polyfill/)已不被推荐，所以后面有必要升级下 babel 且对这块整体做一个优化。 不过在 .babelrc 中配置了 transform-runtime，`babel-polyfill` 也是有引入的价值（根据使用情况），它能够使得新的 API 也可以转换。下面是构建出来的尺寸占比说明图：

![vue-boilerplate-template](https://user-images.githubusercontent.com/15773463/69654495-dc537680-10af-11ea-955a-3273c43f6767.png)

**Comment by jessjava** [comment]
嗯。我基于你的升级到了babel7，使用的是corejs 代替 babel-polyfill，一些webpack新的写法也整理了一下。拜读了你的vue-cli的新工程，总觉得配置收到vue.config.js里面太不自由了。很多想自定义的部分不好写。

**Comment by nicejade** [comment]
@jessjava 嗯，升级至 `babel7` 蛮好的。对于 vue-cli3 这种零配置，对于在 vue.config.js 中配置，略有同感：主要是针对在 chainWebpack 中做一些 loader 的部分，后面没过折腾，也未找寻到更好的办法。
