### ISSUE TITLE
/src/views/demo/List.vue 9:2-221 报错

### ISSUE THREAD

**Issue by niaogege** [nicejade/vue-boilerplate-template#4]
(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.
改个东西就好了：报scope 错误，可能是版本升级到2.5有调整
  _原先_
`<el-table-column label="操作" width="100">
              <template **scope**="scope">
                <el-button @click="onEditClick(scope.row, scope.$index)" type="primary" size="small">编辑</el-button>
              </template>
            </el-table-column>`
_改成_
`<el-table-column label="操作" width="100">
              <template **slot-scope**="scope">
                <el-button @click="onEditClick(scope.row, scope.$index)" type="primary" size="small">编辑</el-button>
              </template>
            </el-table-column>`

**Comment by nicejade** [comment]
@niaogege 的确；Vue [作用域插槽](https://cn.vuejs.org/v2/guide/components.html#作用域插槽) 在 v2.1.0  时候加入，到到 V2.5.0 时候，`scope` 已被弃用，需要使用 `slot-scope`；这份 template 还是基于 Vue2.2.1 的，所以如果本地 vue 版本升级到 2.5，会有此问题（如果同意更新，需要额外考虑于 **element-ui** 的兼容性）。当然，这个错误根源在于没有为插件提供较好的版本保护，后续会加以完善；比如使用 `yarn.lock`；感谢您的反馈。

**Comment by niaogege** [comment]
杨兄，微博问了你一个问题
