### ISSUE TITLE
Dll，DllReferencePlugin和CommonsChunkPlugin同时使用问题

### ISSUE THREAD

**Issue by zengguangzhong** [nicejade/vue-boilerplate-template#5]
你好，你的项目里面这3个插件都使用了，CommonsChunkPlugin不是重复了Dll的事情了吗？

**Comment by nicejade** [comment]
引入 `DllPlugin` 和 `DllReferencePlugin`，是为了将较为固定不变的插件，单独抽离提前构建（当然，有些依赖性很强的插件则不行），以加速平常开发时构建速度，也能从另一个维度减小 vendor 的体积；这在 [Webpack 打包优化之体积篇](https://jeffjade.com/2017/08/06/124-webpack-packge-optimization-for-volume/) 有过阐述；这和 CommonsChunkPlugin 是有所区别的。当然，已经打入到 dll 中的 js，则不会再重复打，即 `DllReferencePlugin` 插件的作用（webpack.DllReferencePlugin 用于指导 webpack 打包业务代码时，遇到vendor-manifest.json的中库文件，利用 `vendor.dll.js` 暴露的全局函数进行处理，而不会把库文件也打包进来）。不知道这样的阐述，是否正确且清晰；如发现错误，还请及时给予指正🙌。

**Comment by zengguangzhong** [comment]
恩，你的关于webpack的文章我都仔细看了，受益很多。 DllPlugin 和 DllReferencePlugin的作用我也了解了。如果CommonsChunkPlugin也存在的话会在dist/js下重新打包mainfest.js和vendor.js。反而增大了体积。这刚好证明了CommonsChunkPlugin如下的两个配置也会重新处理Dll处理过的依赖库（vue,vuex,axios,element-ui）。


您项目中的CommonsChunkPlugin 的如下两个配置应该是多余的吧？


new webpack.optimize.CommonsChunkPlugin({
  name: 'manifest',
  chunks: ['vendor']
}),



new webpack.optimize.CommonsChunkPlugin({
  name: 'vendor',
  minChunks: function (module, count) {
    // any required modules inside node_modules are extracted to vendor
    return (
      module.resource &&
      /\.js$/.test(module.resource) &&
      module.resource.indexOf(
        path.join(__dirname, '../node_modules')
      ) === 0
    )
  }
}),

------------------ 原始邮件 ------------------
发件人: "JadeYang(杨琼璞)";<notifications@github.com>;
发送时间: 2017年11月21日(星期二) 晚上8:41
收件人: "nicejade/vue-boilerplate-template"<vue-boilerplate-template@noreply.github.com>;
抄送: "yun"<839545089@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [nicejade/vue-boilerplate-template] Dll，DllReferencePlugin和CommonsChunkPlugin同时使用问题 (#5)




引入 DllPlugin 和 DllReferencePlugin，是为了将较为固定不变的插件，单独抽离提前构建（当然，有些依赖性很强的插件则不行），以加速平常开发时构建速度，也能从另一个维度减小 vendor 的体积；这在 Webpack 打包优化之体积篇 有过阐述；这和 CommonsChunkPlugin 是有所区别的。当然，已经打入到 dll 中的 js，则不会再重复打，即 DllReferencePlugin 插件的作用（webpack.DllReferencePlugin 用于指导 webpack 打包业务代码时，遇到vendor-manifest.json的中库文件，利用 vendor.dll.js 暴露的全局函数进行处理，而不会把库文件也打包进来）。不知道这样的阐述，是否正确且清晰；如发现错误，还请及时给予指正🙌。

**Comment by nicejade** [comment]
@zengguangzhong 很抱歉，因为些原因才回复你。关于 webpack 的 `CommonsChunkPlugin` 插件，可以参见下 [这里](https://github.com/superpig/blog/issues/6#解决方案：)的说法；关于使用它是否增大了体积，在此模板中已经提供了对应命令 `npm run analyz` 可以分析查看（参见 [ReadMe](https://github.com/nicejade/vue-boilerplate-template#usage) 的 “More Command” 部分）；如有其它看法，期待再探讨。
